let Heading = [
  {
    Head: "ID",
    v1: "1",
    v2: "Electronics Accessories",
    v3: "10",
    v4: "500",
    v5: "view",
    Link: "/CategoryView",
  },
  {
    Head: "Name",
    v1: "2",
    v2: "Clothing",
    v3: "10",
    v4: "600",
    v5: "view",
    Link: " /CategoryView",
  },
  {
    Head: "Total Product",
    v1: "3",
    v2: "Health & Beauty ",
    v3: "700",
    v4: "900",
    v5: "view",
    Link: "/CategoryView",
  },
  {
    Head: "Price",
    v1: "4",
    v2: "Home & Lifestyle ",
    v3: "20",
    v4: "800",
    v5: "view",
    Link: " /CategoryView",
  },
  {
    Head: "Action",
    v1: "5",
    v2: "Hardwares",
    v3: "14",
    v4: "1000",
    v5: "view",
    Link: " /CategoryView",
  },
  {
    //Head: "ID",
    v1: "6",
    v2: "Electronics Accessories",
    v3: "10",
    v4: "500",
    v5: "view",
    Link: "/CategoryView",
  },
  {
   // Head: "Name",
    v1: "7",
    v2: "Clothing",
    v3: "10",
    v4: "600",
    v5: "view",
    Link: " /CategoryView",
  },
  {
   // Head: "Total Product",
    v1: "8",
    v2: "Health & Beauty ",
    v3: "700",
    v4: "900",
    v5: "view",
    Link: "/CategoryView",
  },
  {
    //Head: "Price",
    v1: "9",
    v2: "Home & Lifestyle ",
    v3: "20",
    v4: "800",
    v5: "view",
    Link: " /CategoryView",
  },
  {
   // Head: "Action",
    v1: "10",
    v2: "Hardwares",
    v3: "14",
    v4: "1000",
    v5: "view",
    Link: " /CategoryView",
  },
];
export default Heading;
